spring:
  application:
    name: client-01 # 对外暴露的服务名称
  profiles:
    active: test

#  kafka:
#    bootstrap-servers: 192.168.188.128:9092
#    producer:
#      retries: 5
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      batch-size: 100
#      buffer-memory: 33554432
server:
  port: 8552

---
spring:
  profiles: dev

kouhao: kou-dev

---
spring:
  profiles: master

kouhao: kou-master

---
spring:
  profiles: test

kouhao: kou-test






